name: lucknow_healthcare
description: Lucknow Nursing Healthcare Services - Mobile App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # Network & HTTP
  dio: ^5.3.2
  connectivity_plus: ^5.0.1
  
  # Local Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  
  # UI Components
  cupertino_icons: ^1.0.6
  material_design_icons_flutter: ^7.0.7296
  
  # Navigation
  go_router: ^12.1.1
  
  # Forms & Validation
  formz: ^0.6.1
  
  # Date & Time
  intl: ^0.18.1
  
  # Image Handling
  cached_network_image: ^3.3.0
  image_picker: ^1.0.4
  
  # Notifications
  flutter_local_notifications: ^16.1.0
  
  # Permissions
  permission_handler: ^11.0.1
  
  # Location
  geolocator: ^10.1.0
  
  # Payment Integration
  razorpay_flutter: ^1.3.0
  
  # Utils
  uuid: ^4.2.1
  path_provider: ^2.1.1
  
  # Internationalization
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  bloc_test: ^9.1.5
  mockito: ^5.4.2
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/translations/
  
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
