server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: lucknow-healthcare-services
  
  profiles:
    active: dev
  
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/lucknow_healthcare
    username: healthcare_user
    password: healthcare_password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
    open-in-view: false
  
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
    out-of-order: true
  
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  
  redis:
    host: localhost
    port: 6379
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
    # Connection settings
    connect-timeout: 60000ms
    client-type: lettuce

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:your-super-secret-jwt-key-here-change-in-production-this-key-must-be-at-least-512-bits-long-for-hs512-algorithm}
  expiration: ${JWT_EXPIRATION:900000}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000}

# Payment Gateway Configuration
payment:
  gateway:
    mode: ${PAYMENT_GATEWAY_MODE:PAYTM}  # DUMMY, PAYTM, RAZORPAY, STRIPE
    dummy:
      success-rate: ${DUMMY_PAYMENT_SUCCESS_RATE:90}  # 90% success rate
      processing-time: ${DUMMY_PAYMENT_PROCESSING_TIME:2000}  # 2 seconds
  paytm:
    merchant-id: ${PAYTM_MERCHANT_ID:}
    merchant-key: ${PAYTM_MERCHANT_KEY:}
    website: ${PAYTM_WEBSITE:WEBSTAGING}
    industry-type: ${PAYTM_INDUSTRY_TYPE:Retail}
    channel-id-web: ${PAYTM_CHANNEL_ID_WEB:WEB}
    channel-id-mobile: ${PAYTM_CHANNEL_ID_MOBILE:WAP}
    callback-url: ${PAYTM_CALLBACK_URL:http://localhost:8080/api/payments/paytm/callback}
    transaction-url: ${PAYTM_TRANSACTION_URL:https://securegw-stage.paytm.in/order/process}
    status-query-url: ${PAYTM_STATUS_QUERY_URL:https://securegw-stage.paytm.in/order/status}
  razorpay:
    key-id: ${RAZORPAY_KEY_ID:}
    key-secret: ${RAZORPAY_KEY_SECRET:}
    webhook-secret: ${RAZORPAY_WEBHOOK_SECRET:}
  stripe:
    publishable-key: ${STRIPE_PUBLISHABLE_KEY:}
    secret-key: ${STRIPE_SECRET_KEY:}

# Application Configuration
app:
  name: Lucknow Nursing Healthcare Services
  version: 1.0.0
  environment: ${APP_ENVIRONMENT:development}
  url: ${APP_URL:http://localhost:8080}
  
  # Frontend URLs
  frontend-url: ${FRONTEND_URL:http://localhost:3000}
  provider-dashboard-url: ${PROVIDER_DASHBOARD_URL:http://localhost:5174}
  admin-dashboard-url: ${ADMIN_DASHBOARD_URL:http://localhost:5173}
  
  # File Upload Configuration
  upload:
    dir: ${UPLOAD_DIR:./uploads}
    max-file-size: ${MAX_FILE_SIZE:10485760}
    allowed-types: ${ALLOWED_FILE_TYPES:image/jpeg,image/png,application/pdf}
  
  # Business Configuration
  booking:
    advance-notice-hours: ${BOOKING_ADVANCE_NOTICE_HOURS:24}
    cancellation-window-hours: ${CANCELLATION_WINDOW_HOURS:2}
    emergency-response-time-minutes: ${EMERGENCY_RESPONSE_TIME_MINUTES:15}

# Security Configuration
security:
  bcrypt-rounds: ${BCRYPT_ROUNDS:12}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173,http://localhost:5174}
  rate-limit:
    requests: ${RATE_LIMIT_REQUESTS:100}
    window: ${RATE_LIMIT_WINDOW:60000}

# Notification Configuration
notification:
  email:
    enabled: ${NOTIFICATION_EMAIL_ENABLED:true}
  sms:
    enabled: ${NOTIFICATION_SMS_ENABLED:false}
  push:
    enabled: ${NOTIFICATION_PUSH_ENABLED:false}

# Twilio SMS Configuration
twilio:
  account-sid: ${TWILIO_ACCOUNT_SID:your_account_sid_here}
  auth-token: ${TWILIO_AUTH_TOKEN:your_auth_token_here}
  phone-number: ${TWILIO_PHONE_NUMBER:+1234567890}
  development-mode: ${TWILIO_DEVELOPMENT_MODE:true}
  otp:
    expiry-minutes: 5
    max-attempts: 3

# Logging Configuration
logging:
  level:
    com.lucknow.healthcare: ${LOG_LEVEL:INFO}
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: ${LOG_FILE:./logs/application.log}

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

# Documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
