server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: lucknow-healthcare-services
  
  profiles:
    active: dev
  
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/lucknow_healthcare
    username: healthcare_user
    password: healthcare_password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
    open-in-view: false
  
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
  
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  
  redis:
    host: localhost
    port: 6379
    password: ${REDIS_PASSWORD:}
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:your-super-secret-jwt-key-here-change-in-production}
  expiration: ${JWT_EXPIRATION:900000}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000}

# Payment Gateway Configuration
payment:
  razorpay:
    key-id: ${RAZORPAY_KEY_ID:}
    key-secret: ${RAZORPAY_KEY_SECRET:}
  stripe:
    publishable-key: ${STRIPE_PUBLISHABLE_KEY:}
    secret-key: ${STRIPE_SECRET_KEY:}

# Application Configuration
app:
  name: Lucknow Nursing Healthcare Services
  version: 1.0.0
  environment: ${APP_ENVIRONMENT:development}
  url: ${APP_URL:http://localhost:8080}
  
  # Frontend URLs
  frontend-url: ${FRONTEND_URL:http://localhost:3000}
  provider-dashboard-url: ${PROVIDER_DASHBOARD_URL:http://localhost:3001}
  admin-dashboard-url: ${ADMIN_DASHBOARD_URL:http://localhost:3002}
  
  # File Upload Configuration
  upload:
    dir: ${UPLOAD_DIR:./uploads}
    max-file-size: ${MAX_FILE_SIZE:10485760}
    allowed-types: ${ALLOWED_FILE_TYPES:image/jpeg,image/png,application/pdf}
  
  # Business Configuration
  booking:
    advance-notice-hours: ${BOOKING_ADVANCE_NOTICE_HOURS:24}
    cancellation-window-hours: ${CANCELLATION_WINDOW_HOURS:2}
    emergency-response-time-minutes: ${EMERGENCY_RESPONSE_TIME_MINUTES:15}

# Security Configuration
security:
  bcrypt-rounds: ${BCRYPT_ROUNDS:12}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:3001,http://localhost:3002}
  rate-limit:
    requests: ${RATE_LIMIT_REQUESTS:100}
    window: ${RATE_LIMIT_WINDOW:60000}

# Notification Configuration
notification:
  email:
    enabled: ${NOTIFICATION_EMAIL_ENABLED:true}
  sms:
    enabled: ${NOTIFICATION_SMS_ENABLED:false}
  push:
    enabled: ${NOTIFICATION_PUSH_ENABLED:false}

# Logging Configuration
logging:
  level:
    com.lucknow.healthcare: ${LOG_LEVEL:INFO}
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: ${LOG_FILE:./logs/application.log}

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

# Documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
